[package]
name = "student_db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "*"
postgres = { version = "*", features = ["with-chrono-0_4"] }
chrono = "*"
